CREATE DATABASE IF NOT EXISTS world DEFAULT CHARSET = utf8;

USE world;

CREATE TABLE City (
  ID INT(11) PRIMARY KEY AUTO_INCREMENT,
  Name CHAR(35) NOT NULL,
  CountryCode CHAR(3) NOT NULL,
  Zone CHAR(20) NOT NULL,
  Population INT(11) NOT NULL); 

INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('New York','USA','New York','8008278');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Los Angeles','USA','California','3694820');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Chicago','USA','Illinois','2896016');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Houston','USA','Texas','1953631');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Philadelphia','USA','Pennsylvania','1517550');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Phoenix','USA','Arizona','1321045');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('San Diego','USA','California','1223400');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Dallas','USA','Texas','1188580');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('San Antonio','USA','Texas','1144646');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Detroit','USA','Michigan','951270');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('San Jose','USA','California','894943');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Indianapolis','USA','Indiana','791926');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('San Francisco','USA','California','776733');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Jacksonville','USA','Florida','735167');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Columbus','USA','Ohio','711470');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Austin','USA','Texas','656562');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Baltimore','USA','Maryland','651154');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Memphis','USA','Tennessee','650100');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Milwaukee','USA','Wisconsin','596974');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Boston','USA','Massachusetts','589141');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Washington','USA','District of Columbia','572059');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Nashville-Davidson','USA','Tennessee','569891');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('El Paso','USA','Texas','563662');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Seattle','USA','Washington','563374');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Denver','USA','Colorado','554636');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Charlotte','USA','North Carolina','540828');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Fort Worth','USA','Texas','534694');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Portland','USA','Oregon','529121');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Oklahoma City','USA','Oklahoma','506132');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Tucson','USA','Arizona','486699');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('New Orleans','USA','Louisiana','484674');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Las Vegas','USA','Nevada','478434');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Cleveland','USA','Ohio','478403');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Long Beach','USA','California','461522');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Albuquerque','USA','New Mexico','448607');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Kansas City','USA','Missouri','441545');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Fresno','USA','California','427652');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Virginia Beach','USA','Virginia','425257');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Atlanta','USA','Georgia','416474');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Sacramento','USA','California','407018');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Oakland','USA','California','399484');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Mesa','USA','Arizona','396375');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Tulsa','USA','Oklahoma','393049');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Omaha','USA','Nebraska','390007');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Minneapolis','USA','Minnesota','382618');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Honolulu','USA','Hawaii','371657');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Miami','USA','Florida','362470');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Colorado Springs','USA','Colorado','360890');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Saint Louis','USA','Missouri','348189');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Wichita','USA','Kansas','344284');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Santa Ana','USA','California','337977');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Pittsburgh','USA','Pennsylvania','334563');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Arlington','USA','Texas','332969');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Cincinnati','USA','Ohio','331285');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Anaheim','USA','California','328014');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Toledo','USA','Ohio','313619');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Tampa','USA','Florida','303447');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Buffalo','USA','New York','292648');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Saint Paul','USA','Minnesota','287151');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Corpus Christi','USA','Texas','277454');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Aurora','USA','Colorado','276393');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Raleigh','USA','North Carolina','276093');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Newark','USA','New Jersey','273546');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Lexington-Fayette','USA','Kentucky','260512');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Anchorage','USA','Alaska','260283');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Louisville','USA','Kentucky','256231');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Riverside','USA','California','255166');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Saint Petersburg','USA','Florida','248232');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Bakersfield','USA','California','247057');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Stockton','USA','California','243771');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Birmingham','USA','Alabama','242820');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Jersey City','USA','New Jersey','240055');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Norfolk','USA','Virginia','234403');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Baton Rouge','USA','Louisiana','227818');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Hialeah','USA','Florida','226419');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Lincoln','USA','Nebraska','225581');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Greensboro','USA','North Carolina','223891');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Plano','USA','Texas','222030');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Rochester','USA','New York','219773');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Glendale','USA','Arizona','218812');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Akron','USA','Ohio','217074');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Garland','USA','Texas','215768');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Madison','USA','Wisconsin','208054');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Fort Wayne','USA','Indiana','205727');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Fremont','USA','California','203413');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Scottsdale','USA','Arizona','202705');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Montgomery','USA','Alabama','201568');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Shreveport','USA','Louisiana','200145');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Augusta-Richmond County','USA','Georgia','199775');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Lubbock','USA','Texas','199564');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Chesapeake','USA','Virginia','199184');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Mobile','USA','Alabama','198915');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Des Moines','USA','Iowa','198682');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Grand Rapids','USA','Michigan','197800');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Richmond','USA','Virginia','197790');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Yonkers','USA','New York','196086');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Spokane','USA','Washington','195629');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Glendale','USA','California','194973');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Tacoma','USA','Washington','193556');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Irving','USA','Texas','191615');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Huntington Beach','USA','California','189594');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Modesto','USA','California','188856');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Durham','USA','North Carolina','187035');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Columbus','USA','Georgia','186291');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Orlando','USA','Florida','185951');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Boise City','USA','Idaho','185787');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Winston-Salem','USA','North Carolina','185776');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('San Bernardino','USA','California','185401');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Jackson','USA','Mississippi','184256');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Little Rock','USA','Arkansas','183133');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Salt Lake City','USA','Utah','181743');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Reno','USA','Nevada','180480');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Newport News','USA','Virginia','180150');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Chandler','USA','Arizona','176581');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Laredo','USA','Texas','176576');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Henderson','USA','Nevada','175381');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Arlington','USA','Virginia','174838');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Knoxville','USA','Tennessee','173890');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Amarillo','USA','Texas','173627');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Providence','USA','Rhode Island','173618');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Chula Vista','USA','California','173556');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Worcester','USA','Massachusetts','172648');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Oxnard','USA','California','170358');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Dayton','USA','Ohio','166179');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Garden Grove','USA','California','165196');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Oceanside','USA','California','161029');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Tempe','USA','Arizona','158625');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Huntsville','USA','Alabama','158216');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Ontario','USA','California','158007');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Chattanooga','USA','Tennessee','155554');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Fort Lauderdale','USA','Florida','152397');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Springfield','USA','Massachusetts','152082');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Springfield','USA','Missouri','151580');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Santa Clarita','USA','California','151088');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Salinas','USA','California','151060');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Tallahassee','USA','Florida','150624');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Rockford','USA','Illinois','150115');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Pomona','USA','California','149473');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Metairie','USA','Louisiana','149428');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Paterson','USA','New Jersey','149222');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Overland Park','USA','Kansas','149080');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Santa Rosa','USA','California','147595');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Syracuse','USA','New York','147306');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Kansas City','USA','Kansas','146866');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Hampton','USA','Virginia','146437');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Lakewood','USA','Colorado','144126');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Vancouver','USA','Washington','143560');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Irvine','USA','California','143072');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Aurora','USA','Illinois','142990');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Moreno Valley','USA','California','142381');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Pasadena','USA','California','141674');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Hayward','USA','California','140030');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Brownsville','USA','Texas','139722');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Bridgeport','USA','Connecticut','139529');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Hollywood','USA','Florida','139357');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Warren','USA','Michigan','138247');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Torrance','USA','California','137946');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Eugene','USA','Oregon','137893');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Pembroke Pines','USA','Florida','137427');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Salem','USA','Oregon','136924');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Pasadena','USA','Texas','133936');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Escondido','USA','California','133559');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Sunnyvale','USA','California','131760');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Savannah','USA','Georgia','131510');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Fontana','USA','California','128929');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Orange','USA','California','128821');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Naperville','USA','Illinois','128358');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Alexandria','USA','Virginia','128283');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Rancho Cucamonga','USA','California','127743');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Grand Prairie','USA','Texas','127427');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('East Los Angeles','USA','California','126379');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Fullerton','USA','California','126003');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Corona','USA','California','124966');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Flint','USA','Michigan','124943');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Paradise','USA','Nevada','124682');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Mesquite','USA','Texas','124523');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Sterling Heights','USA','Michigan','124471');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Sioux Falls','USA','South Dakota','123975');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('New Haven','USA','Connecticut','123626');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Topeka','USA','Kansas','122377');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Concord','USA','California','121780');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Evansville','USA','Indiana','121582');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Hartford','USA','Connecticut','121578');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Fayetteville','USA','North Carolina','121015');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Cedar Rapids','USA','Iowa','120758');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Elizabeth','USA','New Jersey','120568');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Lansing','USA','Michigan','119128');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Lancaster','USA','California','118718');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Fort Collins','USA','Colorado','118652');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Coral Springs','USA','Florida','117549');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Stamford','USA','Connecticut','117083');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Thousand Oaks','USA','California','117005');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Vallejo','USA','California','116760');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Palmdale','USA','California','116670');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Columbia','USA','South Carolina','116278');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('El Monte','USA','California','115965');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Abilene','USA','Texas','115930');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('North Las Vegas','USA','Nevada','115488');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Ann Arbor','USA','Michigan','114024');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Beaumont','USA','Texas','113866');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Waco','USA','Texas','113726');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Macon','USA','Georgia','113336');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Independence','USA','Missouri','113288');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Peoria','USA','Illinois','112936');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Inglewood','USA','California','112580');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Springfield','USA','Illinois','111454');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Simi Valley','USA','California','111351');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Lafayette','USA','Louisiana','110257');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Gilbert','USA','Arizona','109697');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Carrollton','USA','Texas','109576');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Bellevue','USA','Washington','109569');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('West Valley City','USA','Utah','108896');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Clarksville','USA','Tennessee','108787');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Costa Mesa','USA','California','108724');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Peoria','USA','Arizona','108364');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('South Bend','USA','Indiana','107789');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Downey','USA','California','107323');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Waterbury','USA','Connecticut','107271');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Manchester','USA','New Hampshire','107006');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Allentown','USA','Pennsylvania','106632');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('McAllen','USA','Texas','106414');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Joliet','USA','Illinois','106221');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Lowell','USA','Massachusetts','105167');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Provo','USA','Utah','105166');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('West Covina','USA','California','105080');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Wichita Falls','USA','Texas','104197');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Erie','USA','Pennsylvania','103717');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Daly City','USA','California','103621');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Citrus Heights','USA','California','103455');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Norwalk','USA','California','103298');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Gary','USA','Indiana','102746');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Berkeley','USA','California','102743');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Santa Clara','USA','California','102361');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Green Bay','USA','Wisconsin','102313');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Cape Coral','USA','Florida','102286');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Arvada','USA','Colorado','102153');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Pueblo','USA','Colorado','102121');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Sandy','USA','Utah','101853');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Athens-Clarke County','USA','Georgia','101489');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Cambridge','USA','Massachusetts','101355');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Westminster','USA','Colorado','100940');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('San Buenaventura','USA','California','100916');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Portsmouth','USA','Virginia','100565');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Livonia','USA','Michigan','100545');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Burbank','USA','California','100316');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Clearwater','USA','Florida','99936');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Midland','USA','Texas','98293');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Davenport','USA','Iowa','98256');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Mission Viejo','USA','California','98049');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Miami Beach','USA','Florida','97855');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Sunrise Manor','USA','Nevada','95362');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('New Bedford','USA','Massachusetts','94780');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('El Cajon','USA','California','94578');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Norman','USA','Oklahoma','94193');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Richmond','USA','California','94100');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Albany','USA','New York','93994');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Brockton','USA','Massachusetts','93653');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Roanoke','USA','Virginia','93357');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Billings','USA','Montana','92988');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Compton','USA','California','92864');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Gainesville','USA','Florida','92291');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Fairfield','USA','California','92256');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Arden-Arcade','USA','California','92040');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('San Mateo','USA','California','91799');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Visalia','USA','California','91762');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Boulder','USA','Colorado','91238');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Cary','USA','North Carolina','91213');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Santa Monica','USA','California','91084');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Fall River','USA','Massachusetts','90555');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Kenosha','USA','Wisconsin','89447');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Elgin','USA','Illinois','89408');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Odessa','USA','Texas','89293');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Carson','USA','California','89089');
INSERT INTO City (Name, CountryCode, Zone, Population) VALUES ('Charleston','USA','South Carolina','89063');
